# Generated by Django 4.0.7 on 2022-12-29 01:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pevent_id', models.CharField(max_length=100)),
                ('participant_email', models.EmailField(max_length=100)),
                ('participant_name', models.CharField(max_length=100)),
                ('participant_contactno', models.IntegerField()),
                ('group_registration', models.BooleanField()),
                ('no_of_members', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(default=uuid.uuid4, max_length=100)),
                ('event_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_name', models.CharField(max_length=120)),
                ('event_start', models.DateTimeField()),
                ('event_end', models.DateTimeField()),
                ('host_email', models.EmailField(max_length=100)),
                ('host_name', models.CharField(max_length=100)),
                ('event_description', models.CharField(max_length=300)),
                ('registration_deadline', models.DateTimeField()),
                ('event_poster', models.URLField(default='', max_length=150)),
                ('event_participants', models.CharField(default='', max_length=10000)),
                ('event_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
